version: "3.4"

services:
  opa:
    image: openpolicyagent/opa:0.40.0-dev-rootless
    container_name: opa
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
      - "run"
      - "--server"
      - "--format=pretty" # pretty, json
      - "--log-level=debug"
      - "--watch"
      - "--bundle=true"
      # - "policy"
      - "/policy/bundle.tar.gz"
      # - "app_rbac.rego"
      # - "roles:data.json"
    volumes:
      - ./policy:/policy
    networks:
      - opa

networks:
  opa:
    driver: bridge